import Category from "@/components/category/Category";
import Header from "@/components/header/Header";
import type { Metadata } from "next";
import { Quicksand, Hind_Siliguri } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

const hindSiliguri = Hind_Siliguri({
  variable: "--font-hind-siliguri",
  subsets: ["bengali", "latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "বাজারদর",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="bn"
      data-theme="light"
      className={`${hindSiliguri.variable} ${quicksand.variable} h-full antialiased`}
    >
      <body className="min-h-full">
        <Header />
        <Suspense
          fallback={
            <div className="border border-[#F0F5F0] bg-componentColor">
              <div className="mx-auto w-full max-w-6xl px-4 py-4">
                <div className="h-8 w-full animate-pulse rounded-lg bg-zinc-200" />
              </div>
            </div>
          }
        >
          <Category />
        </Suspense>
        {children}
      </body>
    </html>
  );
}