import Category from "@/components/category/Category";
import Header from "@/components/header/Header";
import type { Metadata } from "next";
import { Quicksand, Hind_Siliguri } from "next/font/google";
import "./globals.css";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

const hindSiliguri = Hind_Siliguri({
  variable: "--font-hind-siliguri",
  subsets: ["bengali", "latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "বাজারদর ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={` ${hindSiliguri.variable} ${quicksand.variable} h-full antialiased`}
    >
      <body className="min-h-full">
        <Header />
        <Category />
        {children}
      </body>
    </html>
  );
}
