import Category from "@/components/category/Category";
import Header from "@/components/header/Header";
import type { Metadata } from "next";
import { Quicksand, Hind_Siliguri } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
// import MarqueeWrapper from "@/components/marquee/MarqueeWrapper";
import MarqueeText from "@/components/marquee/MarqueeText";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

const hindSiliguri = Hind_Siliguri({
  variable: "--font-hind-siliguri",
  subsets: ["bengali", "latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "বাজারদর",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="bn"
      data-theme="light"
      className={`${hindSiliguri.variable} ${quicksand.variable} h-full antialiased`}
    >
      <body className="min-h-full">
        <Header/>
          <Category />
          {/* <MarqueeWrapper /> */}
          <MarqueeText/>
        {children}
      </body>
    </html>
  );
}
